### ISSUE TITLE
Readme unclear about reconnect

### ISSUE THREAD

**Issue by ForbesLindesay** [Raynos/boot#1]
The readme says "connection you get from shoe will magically handle re-connection logic" but also that "reconnection logic" is something provided by boot?  Is it an extra provided by boot, or something you already get from shoe?

**Comment by Raynos** [comment]
@ForbesLindesay it's something boot does for you. HOWEVER Don't use it.

Use dominictarr/reconnect instead!

**Comment by ForbesLindesay** [comment]
Thanks, I was wondering if there was something to handle reconnect without mux/demux.
